
def my_func():
    my_local = 4
    print("value of var inside the func: " , my_local)

my_func() 
#print("outside the func: " , my_local) # my_local isn't defined diye hata veriyor